from __future__ import annotations

import json

from cairn.dispatcher.config import WorkerConfig
from cairn.dispatcher.workers.base import DriverResult, WorkerDriver


class OpenCodeDriver(WorkerDriver):
    """opencode CLI driver.

    Uses `opencode run --auto --format json` for non-interactive execution.
    Session ids are generated by opencode on first run and parsed from JSON
    output (no pre-seeding). Conclude resumes via `-s <session>`.
    """

    type_name = "opencode"

    def supports_conclude(self) -> bool:
        return True

    def build_healthcheck(self, worker: WorkerConfig) -> list[str]:
        return [
            "opencode",
            "run",
            "--auto",
            "--format",
            "json",
            "-m",
            worker.env["OPENCODE_MODEL"],
            "Reply with exactly: pong",
        ]

    def build_execute(self, worker: WorkerConfig, prompt: str, session: str | None) -> DriverResult:
        argv = [
            "opencode",
            "run",
            "--auto",
            "--format",
            "json",
            "-m",
            worker.env["OPENCODE_MODEL"],
            "--",
            prompt,
        ]
        return DriverResult(argv=argv, session=session)

    def build_conclude(self, worker: WorkerConfig, prompt: str, session: str) -> list[str]:
        return [
            "opencode",
            "run",
            "--auto",
            "--format",
            "json",
            "-m",
            worker.env["OPENCODE_MODEL"],
            "-s",
            session,
            "--",
            prompt,
        ]

    def extract_session(self, session: str | None, stdout: str, stderr: str) -> str | None:
        if session:
            return session
        for line in stdout.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                event = json.loads(line)
            except (json.JSONDecodeError, ValueError):
                continue
            sid = event.get("sessionID")
            if sid:
                return sid
        return None

    def extract_response_text(self, stdout: str, stderr: str) -> str:
        parts: list[str] = []
        for line in stdout.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                event = json.loads(line)
            except (json.JSONDecodeError, ValueError):
                continue
            part = event.get("part")
            if not isinstance(part, dict):
                continue
            if part.get("type") == "text" and "text" in part:
                parts.append(part["text"])
        return "\n".join(parts) if parts else stdout
